### ISSUE TITLE
Ingesting of volume fails

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#402]
I've just done a test-ingest of a serial provided by UB-Frankfurt. The PI process runs fine and ingested works as well except for the volume level ingest.

Can you please review the error and indicate what's wrong?

The Job-ID of spring-batch is 84, the error message returned is:
com.bhle.ingest.batch.IngestException: com.yourmediashelf.fedora.client.FedoraClientException: HTTP 500 Error: javax.ws.rs.WebApplicationException: org.fcrepo.server.errors.ObjectIntegrityException: FOXML IO stream was bad : The value of the attribute "prefix="xmlns",localpart="mods",rawname="xmlns:mods"" is invalid. Prefixed namespace bindings may not be empty. at org.fcrepo.server.rest.BaseRestResource.handleException(BaseRestResource.java:168) at org.fcrepo.server.rest.FedoraObjectResource.createObject(FedoraObjectResource.java:298) at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) at java.lang.reflect.Method.invoke(Method.java:597) at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:175) at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:67) at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:163) at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:71) at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:111) at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:63) at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:689) at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:647) at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:638) at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:309) at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:425) at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:590) at javax.servlet.http.HttpServlet.service(HttpServlet.java:717) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at org.fcrepo.server.security.servletfilters.FilterRestApiFlash.doFilter(FilterRestApiFlash.java:79) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235) at org.apache.ca

Judging from the message there seems to be a problem with the XML!

@lobajuluwa 
@chris-sleep

**Comment by zhengl** [comment]
The error happens in mods:recordContentSource, this tag has multiple namespace (one enclosed and one outside in mods:relatedItem). Removing the namespace definition in mods:recordContentSource can fix the problem.

**Comment by wkollernhm** [comment]
I fixed this namespacing issue and tried to re-ingest the serial, however it now seems as if spring-batch is frozen (I can't view the job list). Can you check this please?

**Comment by zhengl** [comment]
Yes, I can see spring-batch is somehow frozen, but after a short while it resumed.

**Comment by wkollernhm** [comment]
@ZhengLIAtos 
Unfortunately pl-pas content is failing with the exact same error message. Can you please find out what exactly the problem is? All article level metadata is failing.

See Spring-Batch job ID 513 for an example

Is it possible to make the error messages more informational? Unfortunately there is no line number or anything printed out.

**Comment by zhengl** [comment]
@wkollernhm 
The problem is similar to the previous one - duplicate namespace definition. In the example you took (/mnt/nfs/upload/providers/pl-pas/app/app/app32/app32_0151/.aip/bhle_10706_a0573n71.xml), mods:identifier has a redundant mods namespace definition, which has been defined in mods:relatedItem.

I really wish to make these native error messages from Fedora more informative. But since they are thrown by SAX parser and I have no way to retrace to line number. All I can do now is just to gradually narrow down the suspected area...
